controller_manager: controller_manager
controller_list:
- name: cyton_arm/cyton_arm_joint_controller
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  defaul: true
  joints:
    - shoulder_roll_joint
    - shoulder_pitch_joint
    - shoulder_yaw_joint
    - elbow_pitch_joint
    - elbow_yaw_joint
    - wrist_pitch_joint
    - wrist_roll_joint
    - gripper_joint

