// Generated by gencpp from file my_dynamixel_tutorial/SetSpeed.msg
// DO NOT EDIT!


#ifndef MY_DYNAMIXEL_TUTORIAL_MESSAGE_SETSPEED_H
#define MY_DYNAMIXEL_TUTORIAL_MESSAGE_SETSPEED_H

#include <ros/service_traits.h>


#include <my_dynamixel_tutorial/SetSpeedRequest.h>
#include <my_dynamixel_tutorial/SetSpeedResponse.h>


namespace my_dynamixel_tutorial
{

struct SetSpeed
{

typedef SetSpeedRequest Request;
typedef SetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeed
} // namespace my_dynamixel_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_dynamixel_tutorial::SetSpeed > {
  static const char* value()
  {
    return "4641bb0523a3557209606d9bd91ce33a";
  }

  static const char* value(const ::my_dynamixel_tutorial::SetSpeed&) { return value(); }
};

template<>
struct DataType< ::my_dynamixel_tutorial::SetSpeed > {
  static const char* value()
  {
    return "my_dynamixel_tutorial/SetSpeed";
  }

  static const char* value(const ::my_dynamixel_tutorial::SetSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::my_dynamixel_tutorial::SetSpeedRequest> should match 
// service_traits::MD5Sum< ::my_dynamixel_tutorial::SetSpeed > 
template<>
struct MD5Sum< ::my_dynamixel_tutorial::SetSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_dynamixel_tutorial::SetSpeed >::value();
  }
  static const char* value(const ::my_dynamixel_tutorial::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_dynamixel_tutorial::SetSpeedRequest> should match 
// service_traits::DataType< ::my_dynamixel_tutorial::SetSpeed > 
template<>
struct DataType< ::my_dynamixel_tutorial::SetSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::my_dynamixel_tutorial::SetSpeed >::value();
  }
  static const char* value(const ::my_dynamixel_tutorial::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_dynamixel_tutorial::SetSpeedResponse> should match 
// service_traits::MD5Sum< ::my_dynamixel_tutorial::SetSpeed > 
template<>
struct MD5Sum< ::my_dynamixel_tutorial::SetSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_dynamixel_tutorial::SetSpeed >::value();
  }
  static const char* value(const ::my_dynamixel_tutorial::SetSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_dynamixel_tutorial::SetSpeedResponse> should match 
// service_traits::DataType< ::my_dynamixel_tutorial::SetSpeed > 
template<>
struct DataType< ::my_dynamixel_tutorial::SetSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::my_dynamixel_tutorial::SetSpeed >::value();
  }
  static const char* value(const ::my_dynamixel_tutorial::SetSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_DYNAMIXEL_TUTORIAL_MESSAGE_SETSPEED_H
